---
title: "G-Comp"
author: "Coco Kusiak, Hachem Saddiki, and Krishna Vemuri"
date: "12/6/2017"
output: pdf_document
---

```{r set_up}
require(mosaic)
load("obs_data.Rda")
```  

#The Unadjusted Estimator  

$$\Psi^{un} = E_0(Y|A=1) - E_0(Y|A=0)$$

```{r unadjusted}  
obs.gcomp <- obs.data[complete.cases(obs.data),]
a0 <- filter(obs.gcomp, PhysActive == 0)
a1 <- filter(obs.gcomp, PhysActive == 1)
E_a0 <- mean(as.numeric(a0$SleepTrouble))
E_a1 <- mean(as.numeric(a1$SleepTrouble))
psi_un <- E_a1 - E_a0
psi_un
```

```{r}
load("obs_data_v2.Rda")
obs.gcomp2 <- obs.data[complete.cases(obs.data),]
obs.gcomp2 <- mutate(obs.gcomp2, PhysActive = ifelse(PhysActive == "Yes", 1, 0))
a0 <- filter(obs.gcomp2, PhysActive == 0)
a1 <- filter(obs.gcomp2, PhysActive == 1)
E_a0 <- mean(as.numeric(a0$SleepTrouble))
E_a1 <- mean(as.numeric(a1$SleepTrouble))
psi_un <- E_a1 - E_a0
psi_un
```


#The Parametric G-Computation Estimator  

The G-Computation formula in the context of our problem is:  
$$\Psi(P_0) = E_0[E_0(Y|A=1, W) - E_0(Y|A=0,W)]$$  

We need to condition on $W_d$, $W_h$, and $W_l$ in order for the backdoor criterion to hold and for our target parameter to be identifiable.  


```{r models}
greatest <- glm(SleepTrouble ~ PhysActive + Age + Gender + Race1 + Education + MaritalStatus + HHIncomeMid + HomeOwn +
      HealthGen + DaysPhysHlthBad + DaysMentHlthBad + LittleInterest + Depressed + TVHrsDay + 
      CompHrsDay + AlcoholDay + SmokeNow + RegularMarij + HardDrugs, 
    data = obs.gcomp, family = "binomial")

summary(greatest)
smaller<- glm(SleepTrouble ~ PhysActive + Age + Gender + Race1 + 
      HealthGen + DaysPhysHlthBad + DaysMentHlthBad + HardDrugs, 
    data = obs.gcomp, family = "binomial")
summary(smaller)
smaller2<- glm(SleepTrouble ~ PhysActive + Age + Gender + Race1 + 
      HealthGen + DaysPhysHlthBad + DaysMentHlthBad + HardDrugs, 
    data = obs.gcomp2, family = "binomial")
summary(smaller2)


ObsData <- mutate(ObsData, PhysActive = as.numeric(PhysActive))
project<- glm(SleepTrouble ~ . - DaysMentHlthBad - DaysPhysHlthBad, 
    data = ObsData, family = "binomial")
summary(project)


txt <- mutate(ObsData, PhysActive = 1)
control <- mutate(ObsData, PhysActive = 0)

predict.txt.g <- predict(project, newdata = txt, type = 'response')
predict.control.g <- predict(project, newdata = control, type = 'response')
obs.gcomp <- mutate(ObsData, txt = predict.txt.g, control = predict.control.g)
psi.greatest <- mean(predict.txt.g - predict.control.g)
psi.greatest

```

```{r iteration_1}
txt <- mutate(obs.gcomp, PhysActive = "1")
control <- mutate(obs.gcomp, PhysActive = "0")

predict.txt.g <- predict(greatest, newdata = txt, type = 'response')
predict.control.g <- predict(greatest, newdata = control, type = 'response')
obs.gcomp <- mutate(obs.gcomp, txt = predict.txt.g, control = predict.control.g)
psi.greatest <- mean(predict.txt.g - predict.control.g)
psi.greatest

predict.txt.s <- predict(smaller, newdata = txt, type = 'response')
predict.control.s <- predict(smaller, newdata = control, type = 'response')
obs.gcomp.s <- mutate(obs.gcomp, txt = predict.txt.s, control = predict.control.s)
psi.smaller <- mean(predict.txt.s - predict.control.s)
```

```{r}
txt <- mutate(obs.gcomp2, PhysActive = 1)
control <- mutate(obs.gcomp2, PhysActive = 0)

predict.txt.s2 <- predict(smaller2, newdata = txt, type = 'response')
predict.control.s2 <- predict(smaller2, newdata = control, type = 'response')
obs.gcomp.s2 <- mutate(obs.gcomp2, txt = predict.txt.s2, control = predict.control.s2)
psi.smaller2 <- mean(predict.txt.s2 - predict.control.s2)
psi.smaller2
```


```{r interations_500}
R <- 500
n <- 200

estimates <- matrix(nrow = R, ncol = 3)
for (r in 1:R){
  obs <- sample(x = obs.gcomp, size = n, replace = FALSE)
  txt <- mutate(obs, PhysActive = "1")
  control <- mutate(obs, PhysActive = "0")
  
  model1 <-  glm(SleepTrouble ~ PhysActive + Age + Gender + Race1 + Education + MaritalStatus + HHIncomeMid + HomeOwn +
      HealthGen + DaysPhysHlthBad + DaysMentHlthBad + LittleInterest + Depressed + TVHrsDay + 
      CompHrsDay + AlcoholDay + SmokeNow + RegularMarij + HardDrugs, 
    data = obs, family = "binomial")
  model2 <- glm(SleepTrouble ~ PhysActive + Age + Gender + Race1 + 
      HealthGen + DaysPhysHlthBad + DaysMentHlthBad + HardDrugs, 
    data = obs, family = "binomial")
  model3 <- glm(SleepTrouble ~ PhysActive, data = obs, family = "binomial")
  
  Q1w.1 <- predict(model1, newdata = txt, type = 'response')
  Q1w.2 <- predict(model2, newdata = txt, type = 'response')
  Q1w.3 <- predict(model3, newdata = txt, type = 'response')
  Q0w.1 <- predict(model1, newdata = control, type = 'response')
  Q0w.2 <- predict(model2, newdata = control, type = 'response')
  Q0w.3 <- predict(model3, newdata = control, type = 'response')
  
  psi.hat1 <- mean(Q1w.1 - Q0w.1)
  psi.hat2 <- mean(Q1w.2 - Q0w.2)
  psi.hat3 <- mean(Q1w.3 - Q0w.3)
  
  estimates[r,] <- c(psi.hat1, psi.hat2, psi.hat3)
}

mean.psi1 <- mean(estimates[,1])
mean.psi2 <- mean(estimates[,2])
mean.psi3 <- mean(estimates[,3])
var.psi1 <- var(estimates[,1])
var.psi2 <- var(estimates[,2])
var.psi3 <- var(estimates[,3])
```  


#IPTW  













#TMLE  





